# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pairjour}
  s.version = "6.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Taylor luk", "Khoa Nguyne", "Chad Fowler", "Evan Phoenix", "Rich Kilmer", "Phil Hagelberg"]
  s.date = %q{2010-08-27}
  s.default_executable = %q{pairjour}
  s.description = %q{pair programming using bonjour and git, originalted as a fork of gitjour}
  s.email = %q{taylor.luk@idealian.net}
  s.executables = ["pairjour"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "Manifest.txt",
     "README.md",
     "Rakefile",
     "test/test_pairjour.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/idealian/pairjour}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{pair programming using bonjour and git}
  s.test_files = [
    "test/test_pairjour.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dnssd>, ["~> 1.3"])
    else
      s.add_dependency(%q<dnssd>, ["~> 1.3"])
    end
  else
    s.add_dependency(%q<dnssd>, ["~> 1.3"])
  end
end

